### PR TITLE
Implement wheel odometry

### PR DESCRIPTION
**Pull request by Achllle**
## Description

Wheel odometry is a commonly used form of odometry useful for e.g. localization and mapping.

Default behavior is to not calculate it. It can be enabled using an argument;

```
roslaunch osr_bringup osr.launch enable_odometry:=true
```

## To Do

- [x] needs rigorous testing with all the changes from master recently
- [x] implement proper covariance estimate

### CODE REVIEW

**Comment by Achllle** [comment]
Ignore some changes that git is showing that are already in master, it has trouble with squashed commits and rebases.

Let me know if something is missing or needs explanation!

**Comment by Achllle** [comment]
@apollokit @ericjunkins bump

**Review by apollokit — CHANGES_REQUESTED** [review]
Code looks good, and it runs fine on my rover with ROS1.

Couple things:
- are you going to put in a proper covariance estimate? 
- would be nice to have a little bit of an explanation of the odometry message somewhere in the docs (a .md file in this repo is fine). I would just briefly explain the output of `rostopic echo odom`, as seen in the screencap below

Screenshot from 2021-04-06 18-48-18

**Comment by Achllle** [comment]
Added a reference link and covariance. Since odometry is not enabled by default and is a more advanced option, I don't think we should explain it in the repo. Instead I added a link to my blog.

**Comment by Achllle** [comment]
@apollokit

**Comment by apollokit** [comment]
> Added a reference link and covariance. Since odometry is not enabled by default and is a more advanced option, I don't think we should explain it in the repo. Instead I added a link to my blog.

Can you at least mention [here](https://github.com/Achllle/osr-rover-code/blob/iss63/setup/rover_bringup.md#optional-arguments) what the units are on pose and twist? Or give a link where someone can find out? I understand it's a more advanced option, but seems like its helpfulness is limited without at least some context...

**Comment by Achllle** [comment]
This is the standard ROS odometry message, which is described in the link that I added (did you see the link?). For those who are going to set up a nav stack, they will need odometry at one point, which is what this is for. Someone who doesn't want to build a nav stack shouldn't care about launching odometry in the first place.

**Review by apollokit — APPROVED** [review]

**Comment by apollokit** [comment]
> This is the standard ROS odometry message, which is described in the link that I added (did you see the link?). For those who are going to set up a nav stack, they will need odometry at one point, which is what this is for. Someone who doesn't want to build a nav stack shouldn't care about launching odometry in the first place.

a'ight

**Pull request merged**
