### PR TITLE
Custom startup services --> robot_upstart

### PR DESCRIPTION
**Pull request by Achllle**
The existing systemd services don't always work and are a bit of a pain to set up. [robot_upstart](http://docs.ros.org/melodic/api/robot_upstart/html/#usage) makes this a lot easier.

### CODE REVIEW

**Comment by ericjunkins** [comment]
I remember trying to use the robot_upstart package many years ago and having tons of telesales getting it to work.  But if it is more fleshed out now and easier to work with this would be great

**Comment by ericjunkins** [comment]
I remember trying to use the robot_upstart package many years ago and having tons of issues getting it to work.  But if it is more fleshed out now and easier to work with this would be great

**Comment by Achllle** [comment]
I did run into a problem where robot_upstart launches ROS as a different user which is described [here](http://docs.ros.org/jade/api/robot_upstart/html/install.html#permissions). The way around that for me was to modify the udev rule I already had for serial to set the `OWNER` to my username. Would be good if you could test this on your RPi3.

Setting up the package was super simple though, which is what I decided to switch. We could also have both approaches. Either way I think services in linux are hard.

**Comment by Achllle** [comment]
To be more concrete: Every device that ROS uses must be owned by the same user. I have a usb camera, a raspicam, an IMU that operates through i2c, as well as the default joystick (`/dev/input/js*`) and serial device (`/dev/serial0`). You have to have a udev rule that sets those devices to $USER iso root. That might actually be best practice anyways.

All you would need to do is to create your udev rule 'as normal' and then add `OWNER="$USER"` to it. `ls -l /dev/yourdevice` will then show the owner to be your username iso root.

I can see how this isn't straightforward for the linux novice (or even intermediate). I'd be curious to see if there's a way to have robot_upstart run as user/root.

**Comment by ericjunkins** [comment]
Udev rules certainly can be confusing for those not very familiar with Linux, I think as long as we can provide well documented examples of the structure of how to write the Udev rules it should be fine though

**Comment by Achllle** [comment]
Closing this as we've improved our instructions

**Pull request closed without merging**
