### PR TITLE
Simple contributing guide added to README

### PR DESCRIPTION
**Pull request by pabloriveracelerity**
Per issue #9 :

```Add a CONTRIBUTING.md - helps promote best practices for working on an issue or submitting a PR, sometimes occompanied by a code of conduct. (This one's also still on my backlog of things to do)```

NASA has a website with contributing info (https://code.nasa.gov/#/guide), but I'm not sure if it applies here given that this is a caltech project at heart. @asasine What do you think?

### CODE REVIEW

**Comment by asasine** [comment]
I'm not from NASA or JPL but I believe @vssystemluba is a member of this org; he can probably give a better direction to this.

Traditionally, steps to contribute go into _CONTRIBUTING.md_ and that file is referenced from _README.md_.

**Comment by pabloriveracelerity** [comment]
OK great, let's hope he can chime in.

We can move it to its own file later for sure. I was avoiding adding it to a separate file to keep things simple for now. 👍

**Comment by ericjunkins** [comment]
Sorry for the late response on this, turns out I didn't have a watch on the Submodules only the main Github repo. I think that having a CONTRIBUTING.md referenced from the main README.md is the way to go about this yes

**Comment by pabloriveracelerity** [comment]
I'll split off the contributing content into its own file in the coming days. Thanks for the feedback. 👍

**Pull request merged**
