### PR TITLE
use current radius iso commanded radius to calculate drive velocities

### LINKED ISSUE #66: Smoother and synchronized steering
Instead of using position control, use a velocity controller (or even torque) on the corner steering motors. This would allow higher control loop rates to ensure that all wheels are synced up while turning.
Perhaps also the time to switch to ros_control

### LINKED ISSUE #69: Use current radius iso commanded radius to calculate drive velocities
Currently the turning radius used for calculating drive velocities is the commanded velocity as opposed to the current turning radius. This should be easy to do after the overhaul described in #55, #45 and others

### PR DESCRIPTION
**Pull request by Achllle**
## Description

Taking feedback on a way to calculate the current radius given encoder readings. I implemented a simple way of doing this using the median value of the calculated radii according to each motor position. There's probably other good ways of doing this. 
close #69 , close #66 
The idea behind calling the method `forward_kinematics` is that I intend to calculate the current twist at each time step so that we can keep track of odometry easily in perhaps a follow-up PR.

To get this to work correctly, I also had to fix the the way the rover responds to Twist messages. Before, the angular z component of the twist was treated as the turning angle. This isn't correct. The rotation of the robot over time depends on the linear velocity of the rover. For a fixed steering angle, the twist will be larger when the rover is moving faster. The linear and angular velocity for this type of (ackermann) steering are related by the turning radius:

Now this change affects how the rover drives:

* backward steering is now flipped. Before, when moving the joystick to the left, the wheel axes will always intersect at the left side of the rover ("the wheels will turn left") regardless if you're going forwards or backwards. Now, when going backwards, the wheel axes will intersect on the right side of the rover (positive angular component (counter clockwise)). This might be slightly less intuitive for those used to the old way of driving, but you get used to it quickly. If we want to change this behavior, we should modify the joystick code and not the underlying behavior to simply flip the angular component when the robot is going backwards.
* steering angle is zero when the linear velocity of the rover is zero. Right now, if you want to orient the wheels without moving, you can give it a tiny forward or backward velocity to indicate what direction. This is due to the first point.

## Dependencies

- [x] #79 to avoid merge conflict later, both PRs touch the same methods
- [x] #101

### CODE REVIEW

**Comment by ericjunkins** [comment]
I'll give this a look over tomorrow

**Comment by Achllle** [comment]
@gfosmire or @ericjunkins can either of you review? I have odometry ready and this is a dependency for that

**Comment by Achllle** [comment]
We want to keep the underlying adherence to the twist but want to keep joystick be intuitive. So we need to figure out how to flip the steering when negative.

**Comment by Achllle** [comment]
Instead of changing the input, I'll just add another callback+topic for both. We'll connect the joystick output to the modified, more intuitive one but still have the mathematically correct one for any nav stacks

**Comment by Achllle** [comment]
@gfosmire and @ericjunkins As mentioned before, I added a separate callback as the default which is more intuitive for controlling the robot. The mathematically correct one is still there, just under a different topic.

Test on your robot if you can, otherwise I think this is good to go. Works smoothly on my rover.

**Comment by ericjunkins** [comment]
Hey @Achllle, got around to taking a look at this. I had quite a bit of wonkyness trying to control the robot. I attempted to control it both with intuitive mode True and False, both of which led to very strange results, that didn't seem extremely reproducable. Sometimes the corners wouldn't respond to commands on the joystick, and would sometimes turn in response to pressing bumpers on the controller instead. Also is your plan to move to the single unified joystick for controlling? It felt very difficult to control both steering and drive velocity independantly.

**Comment by ericjunkins** [comment]
I guess I also want to make sure we're using the same controllers? with the same mappings? I use the XBOX 360 controller

**Comment by Achllle** [comment]
Hmm that sounds odd. In intuitive (default) mode it should behave the same way as before, did you compare to the latest master? I use the same controller. @apollokit can you see if you get the same result?

Would be good to characterize what you're seeing exactly as right now it just works on mine.

**Comment by Achllle** [comment]
The left joystick controls forward motion while the right controls steering. That is unrelated to this branch though, that was merged in a while ago.

**Comment by Achllle** [comment]
I set the default to be intuitive mode and removed the joystick.py file which should've been removed before.

**Comment by ericjunkins** [comment]
I won't be home for at least a few days here,  @gfosmire can you take a look and see ?

**Comment by apollokit** [comment]
Oh, just saw this. I ran your code and didn't have any problems driving/steering. Honestly it didn't feel any different from master....I'm wondering if I actually ran the new code successfully. Should I expect to see a big difference?

**Comment by Achllle** [comment]
That's good to hear, you should not. The only difference you might feel is that when turning quickly, there is less slip. This makes it so that the drive velocities are calculated based on the current angle of the corner motors as opposed to where it's going.

**Comment by ericjunkins** [comment]
Okay maybe George can give some insight shortly.  It seemed to be pretty significantly different than running the master branch for ours,  not sure where the difference came from though

**Comment by gfosmire** [comment]
So I just ran this version of the code again, tried both intuitive true and false, and saw lots of strange behavior. In addition to the wonkiness Eric and I saw together (things like sometimes the left stick controlling steering, sometimes the bumpers causing turning) another thing I noticed was that even when it was acting "normal" (left stick controlling speed, right stick controlling direction) when I turned there was major slippage is some of the wheels, implying to me that either the wheel angle math or the wheel speed math is off, for ours. I am glad that it seems to be working for Achille and Kit, and will spend some more time trying to isolate the issues/wonkiness.

**Comment by ericjunkins** [comment]
But what is on the current master branch work correctly?

**Comment by gfosmire** [comment]
Did a fresh pull on master and drove it around the living room with ease. No wonkiness, no slippage while turning.

**Comment by Achllle** [comment]
> tried both intuitive true and false

There's no boolean switch for intuitive mode exposed. If you want to disable intuitive mode, remove the `<remap from="/cmd_vel" to="/cmd_vel_intuitive"/>` from the launch file. You should never be touching the code to modify a parameter. That remap command just pipes the data from the joystick to a different topic. I'm not sure if that would matter here though.

I would suggest checking and comparing the topics on each branch . Also make sure you have the latest version pulled from each branch, especially master (I sometimes update from origin when I should be updating from upstream). Is there something unexpected on the:

* /joy topic, or
* /cmd_vel_intuitive or /cmd_vel topic, or
* /drive_cmd and /corner_cmd topics?

That will help isolate where this comes from.

**Comment by gfosmire** [comment]
My pull from master was behind a few commits and updated, so I think it is correct and up to date, but I will confirm this. I will do a fresh pull of this code to make sure I am working with the correct version here too.

Thanks for the suggestions, I will start by checking those things first.

**Comment by apollokit** [comment]
I tried Achille's updated code again, just to make sure I was using the right stuff. Again, doesn't seem different from master. 

Though I'm seeing some weirdness in general from one of my corner motors, and a one gearbox on a drive motor has started coming loose and I can't really tighten it because a bolt is stripped...hrmph. Not sure I'm a great test case here.

**Comment by Achllle** [comment]
@gfosmire any updates on this?

**Comment by ericjunkins** [comment]
@Achllle I looked at all this tonight, and talked with George quite a bit about what he was seeing when he was testing. These are my thoughts:

  - Can you explain to me about this? https://github.com/Achllle/osr-rover-code/blob/6928dc7a091f657a8fc49db4d00f4232681fcd65/ROS/osr/src/rover.py#L201 Why do we want to if there is no x velocity at all peg the turning? What we are seeing is that a very small amount of stick turning maxes the turning radius while there is no x velocity, and that is dampedned as x velocity increases. Should we have a case where the x velocity is in some very small deadband so this doesn't happen?

  - The 'slippage' that George was seeing in the turning I believe is coming from a low sampling rate of the motor controllers compared to the speed in which the corners turn, causing the forward kinematics to predict a value that is then used for the next ~0.1s, which the rove can have a drastically different actual turning radius by the end of. I think this is just something to think about if there is maybe something else to do with forward kinematics. 

Either way, I'm going to green check the PR, we can talk about if we want to look at the above notes at a further time. Good job 👍

**Review by ericjunkins — APPROVED** [review]
👍

**Comment by Achllle** [comment]
Really appreciate these comments! I'll look into it and see if there are any improvements I can make, especially now that I have different motors.

**Comment by Achllle** [comment]
@ericjunkins I made a few changes:

* I changed and clarified conventions for the interpretation of corner motor values. In `roboclaw_wrapper.py` positive values mean positive values around the motor shaft from the motor's perspective (z-axis down). In `rover.py` to make calculations easy, the opposite is true with the z-axis pointing up
* I left the code for calculating current turning radius and publishing odometry, but switched back to using the desired turning radius. I experimented with a hybrid, using current turning radius and future proofing by adding a bit of the desired turning radius, but that's more complicated and I saw some spikes in the turning radius which might explain why you guys were seeing slippage. If we want to switch later, the infrastructure is set up for it.
* I changed the behavior for standing still and turning in intuitive mode. It will use the drive motor velocities to calculate the twist values (similar to how it happens in `osr.launch`) and now when you slightly move the joystick, the wheels will just turn a little bit. In the mathematically correct mode (intuitive=False), the wheels still don't turn when linear velocity is zero (as it should be)

Given that nothing drastically changes compared to master, I'll merge this in. If we see any problems, can always revert.

**Pull request merged**
