### PR TITLE
Send velocity to roboclaws instead of duty cycle

### PR DESCRIPTION
**Pull request by Achllle**
Small fix. Unlike sending duty commands, this requires properly tuned velocity control on the roboclaws, otherwise the wheels will start up at different speeds and put stress on the system or slip.

### CODE REVIEW

**Comment by ericjunkins** [comment]
In thinking about this more, one concern I have is that velocity based closed loop will impact the robots ability to scale obstacles. My intuition is that when driving duty based and you encounter an aggressive obstacle, say a 90deg curb, that there is an ability for the bogie to respond and distribute the forces by pivoting about it's center appropriately, allowing the wheels to then also move at the speed necessary. If you are forcing them all to move at the same speed It might not be able to distribute that appropriately. 

The above is why I want to explore having the option to have both still, if it does have a negative impact on the climbablity of the robot you might not ALWAYS want to drive velocity based then, you might want to switch when encounting obstacles etc. 

I am still a ways away from having the necessary tools at my house to diagnose/fix whatever cable/connector problem my rover has with one of the drive wheels, so I cannot actually test this PR, we are trying to find ways to resolve issues/Prs without that being a blocking factor.

**Comment by Achllle** [comment]
I agree with that. The 'right' way of doing this is to have torque control for each of the wheels and write a velocity controller around that. This is exactly what ros_control is designed for and they have ackermann steering controllers available that can easily be modified to handle 6 wheels (see [the ros controller for the Sawppy rover](https://github.com/srmainwaring/curio/blob/ef09cc3c469de37241b5cde9b5c35f549977bd6f/ackermann_drive_controller/include/ackermann_drive_controller/ackermann_drive_controller.h) and [the implementation we would build off of from ros_controllers](https://github.com/ros-controls/ros_controllers/tree/melodic-devel/ackermann_steering_controller)). This is a little bit of a setup, but I've done it before and happy to start working on it.

What you get is:

1. you can call a service to switch controllers and go from controlling velocity to controlling torque. You can have a controller that's all about just driving the thing around and hitting things while being as safe as possible. That would fit in with you idea regarding different launch files.
2. you can write your velocity controller such that it is quite lenient when sudden bumps happen, and you can even update your odometry covariance knowing that there likely is slip in the wheels.

The only issue is that I'm not entirely sure what duty actually means for the roboclaws. A regular motor driver works by using FETs to turn off and on voltage to the motor terminals based off an incoming PWM. That amounts to voltage control which is velocity control. A true current and thus torque controller senses the current from the motors and adjusts voltage to match a desired current. Few controllers actually do this properly (this requires very tight control and high loop rates, on the order of 10-20kHz), and so I wouldn't be surprised if duty on the roboclaws is just open loop velocity control. What that means is that your are neither controlling current directly nor velocity. The actual current will depend on the load. Now whether that matters is a different question and strongly depends on the system setup (latency, control loop frequency, ...). We could and probably should try it though since there's only advantages in switching.

**Comment by ericjunkins** [comment]
I had thought based on the roboclaw documentation I read what is now years ago that the duty command didn't attempt to do any closed loop control, and was solely an open loop throttling of the PWM signals such that the averaged output over a given time was that percent of the incoming bus voltage. ie. 30% duty command is 0.3 * Vbus, with no attempt to track torque.

**Comment by Achllle** [comment]
That would confirm my suspicion. In which case duty is just open loop velocity control and we can either write our own controller around it to get to the desired velocity control behavior, or we can rely on the built-in velocity controller and just set fairly weak proportional control values so that we get the same behavior as just commanding duty (i.e. compliance to external forces).

The difference is that the latter will never achieve the intended velocity which will making tuning a navigation stack very hard.

**Comment by ericjunkins** [comment]
Merging this PR in, we haven't been able to fully verify with closed loop driving, yet, working on the PR to switch between duty and veloctiy based control today.

**Pull request merged**
