### PR TITLE
Custom configs

### PR DESCRIPTION
**Pull request by Achllle**
## Decription

Force users to at least create a custom config file so folks can easily switch between branches and check out other users code without running the wrong settings on their rover. The modified parameters simply overwrite the default settings if they exist.

### Steps

in osr_bringup/config, `touch physical_properties_mod.yaml roboclaw_params_mod.yaml` or `cp` the default yaml files. 
Add or modify the lines in the `_mod.yaml` files so that they sit in the same namespace as the default files. For example, I want to overwrite the default absolute encoder `ticks_per_rev`, then in `roboclaw_params.yaml`, I add:

```
roboclaw_mapping:
  corner_left_front:
    ticks_per_rev: 1732
  corner_left_back:
    ticks_per_rev: 1714
  corner_right_back:
    ticks_per_rev: 1750
  corner_right_front:
    ticks_per_rev: 1756
```

You can also `cp` the default files, but unless you have to modify everything, I recommend only having the lines that differ from the original.

## Dependencies

- [x] #84 edits to readme so depends on readme update

### CODE REVIEW

**Comment by ericjunkins** [comment]
@Achllle when cloning this and running it I get an error in rover.py, on line 49, 

`global name 'msg_vel' is not defined`

Is the input to drive_cmd_msg supposed to be your velocity variable defined a few lines above?

**Comment by Achllle** [comment]
That's odd. This PR doesn't change any code. I just merged in master so that the dependency on #84 now is fulfilled. Do you get the same when you `git checkout master` after a `git pull origin master`? 
By the way, I'm assuming when you say 'when cloning this', you mean checking out?

**Comment by ericjunkins** [comment]
I'm pretty sure I did the following: 

`git checkout -b Achllle-custom_configs master`
`git pull git://github.com/Achllle/osr-rover-code.git custom_configs`

**Comment by ericjunkins** [comment]
Can give it another look maybe Sunday morning though

**Comment by Achllle** [comment]
Were you able to test? This doesn't touch any code though so that shouldn't even be necessary.
Also please review without merging. That should be left to the assignee.

**Pull request merged**
