### PR TITLE
Use teleop_twist_joy instead of joystick.py

### LINKED ISSUE #13: Adding support for Playstation controllers
Would anyone be interested in a PR for this?

### PR DESCRIPTION
**Pull request by Achllle**
## Description

Instead of write our own joy to twist node, we can just use an existing one, written in C++, tested, easily modifiable for different controller types ( close #13 ): [teleop_twist_joy](http://wiki.ros.org/teleop_twist_joy)

Folks who don't have that installed yet should run
```
rosdep install --from-paths src --ignore-src
```
in their catkin workspace after updating to this commit or to just install this package only via `sudo apt install ros-$ROSDISTRO-teleop-twist-joy`

## Dependencies

- [ ] #79

### CODE REVIEW

**Comment by ericjunkins** [comment]
So this also then requires just a quick change to the build documentation for the software to make sure to do `sudo apt install ros-$ROSDISTRO-teleop-twist-joy` ?

**Comment by Achllle** [comment]
I just added it to the readme in this repo. What makes most sense to me is that the build doc for software just refers to the readme here. Otherwise we'll have to synchronize repos and open a PR there too for every documentation change made here. I can do that if you agree

**Comment by gfosmire** [comment]
@Achllle I pulled this version to our rover, but have been unable to get it to work. I did the sudo apt install, but we already had the latest version of teleop twist. The joy2twis node is running and /joy is publishing but cmd_vel is not publishing.

**Comment by Achllle** [comment]
Are you pressing the enable button while sending commands? Try moving the joystick while holding the 'LB' button.

If that still doesn't work, can you post output from `roswtf` and `rqt_graph`?

**Comment by gfosmire** [comment]
That worked, I didn't know about needing to hold down the LB button. The twist commands look like they are working fine, but I don't know how to resolve the upstream differences since this is many PRs back. I'm kind of a git novice, so I'm not sure how to deal with the differences between this code and the changes I made in a PR I submitted today. How should I/we go about this?

**Comment by Achllle** [comment]
Glad to hear that solved it. I'll make sure to add it to the instructions.

The PR you submitted, #88 seems to be independent from this PR and so the order that they go in should not matter. This PR however does depend on #79 so that should be reviewed and merged before this one can go in

**Comment by mikcox** [comment]
Things look fine to me here as well; @ericjunkins @gfosmire let me know when you all confirm functionality and driveability and we can merge this right after #79.

**Comment by ericjunkins** [comment]
@gfosmire Can you give an update on this? Is this all verified and ready to go? There are a few PRs upstream that depend on this and some of them are very quick easy merges in once this is done

**Pull request merged**
