### PR TITLE
Upgrade permission on ROS executables to executable (chmod+x'd)

### PR DESCRIPTION
**Pull request by Achllle**
Instead of having the user just upgrade permissions in the software install steps instruction sheet (`chmod +x *.py`), these permissions can be changed by default. Here I only change the two executables that are executed as ROS nodes. The other ones don't need the elevated permissions.

## Dependencies

- [ ] #57

### CODE REVIEW

**Comment by Achllle** [comment]
With the file rename in #57 might want to wait until those are merged in and update naming here after

**Comment by ericjunkins** [comment]
@Achllle Can we add the upgrade permission to the arduino_comm.py  in the led_screen package to this as well? Might as well do all the ones at the same time

**Comment by Achllle** [comment]
Done. History is pretty ugly here for essentially a single commit. When you merge, consider using 'squash merge' from the drop-down. Also happy to open a new PR or force-push.

**Comment by ericjunkins** [comment]
I think for this one we'll be okay with squashing, thanks 👍

**Pull request merged**
