### PR TITLE
Addition of Facial Expression: SHOCK

### PR DESCRIPTION
**Pull request by isaacdre**
Sorted and Grouped RGBmatrixPanel Eyes, Cheeks, and Mouths. Added 'shocked_face' (along with child functions 'open_mouth' and 'shocked_eyes'). This added expression can be used / triggered by error events, Accelerometers, etc.

 The main purpose of this extension was to explore the addition of faces, since this seems like an easy position for first-time open source contributors to enter with little cost overhead.
 In the future, I intent to create a README.md and split out the code into sub-files so that it will be easier for first time open source contributors to get the handle on this.
 Educationally, I could see this being an incredible first step for many students whose families / schools don't have the financial resources to afford the whole $2500 rover.

### CODE REVIEW

**Comment by ericjunkins** [comment]
Hi @isaacdre , sorry for the late reply here. I will get along to checking all this out here in the next few days

**Comment by ericjunkins** [comment]
@isaacdre Hey i just took a look at this, the code looks good, I just took the led screen out of the box it was in and found out that it had something break in the actual screen and it no longer displays most of the pixels correctly, I will have to order another one. Would you be able to put some pictures of yours here just so i can check it out? Would be willing to push the merge without running it on mine while I wait for a new screen

**Comment by isaacdre** [comment]
@ericjunkins, No worries! I'm in no rush whatsoever, (I'm actually stoked that the response was so quick!)

I'm in the process of moving my office... and so my prototype kits are buried DEEP... somewhere...

I'll try and send those pics over when I can, but it may be a very long time 😬.

On another note, do you know of any virtual RGB Panels? I know that the panels are cheapish... but it also seems like a barrier to entry to those low on cash. If that doesn't exist... I may start looking into making that another side project because I have no self control when it comes to taking on coding projects.

I'll try and check back in on this before July (I'm aiming to have completely moved and reorganized my office by then!)

**Comment by Achllle** [comment]
While the v2 design of OSR does not have a screen/head in the default design, the code is still available so I've merged this in.

**Pull request merged**
